language: generic

env:
  - TCL_VERSION=8.6.0
  - TCL_VERSION=8.5.13

install:
  - curl -L "http://prdownloads.sourceforge.net/tcl/tcl${TCL_VERSION}-src.tar.gz" | tar xzfv -
  - cd "tcl${TCL_VERSION}/unix"
  - ./configure
  - make
  - sudo make install
  - ln -sf "/usr/local/bin/tclsh$(echo $TCL_VERSION | sed -e 's/\.[0-9]*$//')" /usr/local/bin/tclsh
  - cd ../..

  - curl -L http://sourceforge.net/projects/next-scripting/files/2.0b3/nsf2.0b3.tar.gz/download | tar xzfv -
  - cd nsf2.0b3
  - ./configure
  - make
  - sudo make install
  - cd ..

script: bin/tclspec